#服务端口配置
server:
  port: 8084
  #max-http-header-size: 4048576
  servlet:
    multipart:
      max-file-size: 1000Mb
      max-request-size: 1000Mb
    #context-path: /api
  max-http-header-size: 5120000
   
#服务名称配置
spring:
  application:
    name: Sharingdata
   
  session:
    timeout: 10
    #数据库连接部分
  datasource:
    url: jdbc:sqlite:/Users/h/Documents/nqwwork/nqw-sharingdata/src/main/resources/sharingdata1.db
    username: root
    password: 123456
    driver-class-name: org.sqlite.JDBC
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000

    
#日志配置      
logging:
  level:
    com.palmgo.com.cn.sharingdata.dao: DEBUG  
      
#mybatis配置   
mybatis:
  mapper-locations: classpath:/mybatis/*.xml
  type-aliases-package: com.palmgo.com.cn.sharingdata.bean
  

#服务治理中心配置    
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.30.241:8092/eureka/
  instance:
    prefer-ip-address: true #使用ip地址
    instance-id: ${spring.cloud.client.ip-address}:${server.port}  
    
cache:
  path: ehcache.xml
  
#定时任务  
job:
  datasourcetaskinit: 0 0/30 * * * ?

#自定义配置
common:
  swaggerHost: 127.0.0.1:8084
  licenseUrl: http://127.0.0.1:8084
  version: 1.0
  #接收数据处理队列大小
  globalQueueSize: 100000
  #缓存地址
  cacheServer:
    - 172.16.30.241:7001
  cachetime: 350